"use client"

/*import type { Metadata } from "next";*/
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

  //console.log('currentUrl : '+currentUrl);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //const pageTitle = useRef<HTMLInputElement>(null);
  return (
    <html lang="en">
      <head>
        <title>Invoice Sync App</title>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     
      <header className="bg-gray-100 shadow-md">
          <div className="container-lg mx-auto">
          <div className="navbar">


  <div className="flex-1">
    <a className="btn btn-ghost text-xl" id="TitleLink" ></a>
  </div>
  <div className="flex-none">
    <ul className="menu menu-horizontal px-1">
      <li><a>Link</a></li>
      <li>
        <details>
          <summary>Parent</summary>
          <ul className="bg-base-100 rounded-t-none p-2">
            <li><a>Link 1</a></li>
            <li><a>Link 2</a></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>

</div>
</div>
</header>

        {children}
      </body>
    </html>
  );
}
